### ISSUE TITLE
Injecting to another application requires INJECT_EVENTS permission

### ISSUE THREAD

**Issue by Tsingkai** [cibimo/2021_taobao_1111_autoscript#4]
### 设备及系统
+ MIUI 12.5
+ Mix 2s
+ 可以调通 uiautomator2
+ 界面：领喵糖

### Exception Message
```
D:\System_Icon\Downloads\2021_taobao_1111_autoscript-main> .\taobao.py
Traceback (most recent call last):
  File "D:\System_Icon\Downloads\2021_taobao_1111_autoscript-main\taobao.py", line 60, in <module>
    d(text="赚糖领红包").click()
  File "D:\Python\Python39\lib\site-packages\uiautomator2\_selector.py", line 155, in click
    self.session.click(x, y)
  File "D:\Python\Python39\lib\site-packages\uiautomator2\__init__.py", line 1067, in click
    self.jsonrpc.click(x, y)
  File "D:\Python\Python39\lib\site-packages\uiautomator2\__init__.py", line 480, in __call__
    return self.server._jsonrpc_retry_call(self.method, params,
  File "D:\Python\Python39\lib\site-packages\uiautomator2\__init__.py", line 487, in _jsonrpc_retry_call
    return self._jsonrpc_call(*args, **kwargs)
  File "D:\Python\Python39\lib\site-packages\uiautomator2\__init__.py", line 556, in _jsonrpc_call
    raise err
uiautomator2.exceptions.JSONRPCError: -32001 Jsonrpc error: <java.lang.SecurityException> data: java.lang.SecurityException: Injecting to another application requires INJECT_EVENTS permission
        at android.os.Parcel.createException(Parcel.java:2074)
        at android.os.Parcel.readException(Parcel.java:2042)
        at android.os.Parcel.readException(Parcel.java:1990)
        at android.app.IUiAutomationConnection$Stub$Proxy.injectInputEvent(IUiAutomationConnection.java:471)
        at android.app.UiAutomation.injectInputEvent(UiAutomation.java:597)
        at com.github.uiautomator.stub.TouchController.injectEventSync(TouchController.java:38)
        at com.github.uiautomator.stub.TouchController.touchDown(TouchController.java:47)
        at com.github.uiautomator.stub.AutomatorServiceImpl.click(AutomatorServiceImpl.java:206)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.googlecode.jsonrpc4j.JsonRpcBasicServer.invoke(JsonRpcBasicServer.java:467)
        at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleObject(JsonRpcBasicServer.java:352)
        at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleJsonNodeRequest(JsonRpcBasicServer.java:283)
        at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleRequest(JsonRpcBasicServer.java:251)
        at com.github.uiautomator.stub.AutomatorHttpServer.serve(AutomatorHttpServer.java:100)
        at fi.iki.elonen.NanoHTTPD.serve(NanoHTTPD.java:2244)
        at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
        at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
        at java.lang.Thread.run(Thread.java:919)
, method: click
```

**Comment by cibimo** [comment]
请检查是否允许USB调试修改权限或模拟点击事件

**Comment by Tsingkai** [comment]
MIUI的允许模拟点击叫安全调试……
